### ISSUE TITLE
Cannot work on aarch64 platform Androids(Failed on SONY XZP)

### ISSUE THREAD

**Issue by qtxiaoxiaoshen** [nmilosev/anyfed#4]
it can be fixed by edit anyfed script to change aarch64 download URL

**Comment by nmilosev** [comment]
I don't see that we have `aarch64` Docker image :(

Can you please provide the exact instructions what you did? Maybe it's this mirror that I am looking at.

Cheers!

**Comment by valorad** [comment]
I think the correct  aarch64 URL should be
`http://dl.fedoraproject.org/pub/fedora-secondary/releases/25/Docker/aarch64/images/Fedora-Docker-Base-25-1.3.aarch64.tar.xz`
rather than 
`https://download.fedoraproject.org/pub/fedora/linux/releases/25/Docker/$ARCH/images/Fedora-Docker-Base-25-1.3.$ARCH.tar.xz`

**Comment by f055** [comment]
When installing Fedora with anyfed on Termux on a SONY Xperia Z4 Tablet I encountered the same issue as https://github.com/nmilosev/termux-fedora/issues/4 – probably since I selected the `armhfp` architecture. However, by updating the anyfed bash script with the image URL from @valorad and typing the architecture name as `aarch64`, everything installed fine. I suggest updating the download image URL to one that supports all the available architectures and updating the first question to something like `Which architecture do you need? (armhfp, aarch64, [x86_64])`

**Comment by nmilosev** [comment]
Thanks for your help, this is now added to anyfed.

Cheers!
